upstream starcdn_backend {
    server starcdn-backend:2606;
}

server {
    listen 2607;
    server_name _;

    location / {
        proxy_pass http://starcdn_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
